name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 – Check out code
      - uses: actions/checkout@v4

      # 2 – Set up pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3 – Install dependencies (inside the sub-folder)
      - name: Install packages
        run: pnpm install
        working-directory: stock-inventory-app   # 👈 change if your folder name differs

      # 4 – Run tests
      - name: Test
        run: pnpm run test -- --run
        working-directory: stock-inventory-app

      # 5 – Build production bundle
      - name: Build
        run: pnpm run build
        working-directory: stock-inventory-app
