name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 – Check out code
      - uses: actions/checkout@v4

      # 2 – Set up pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3 – Install dependencies
      - name: Install packages
        run: pnpm install
        working-directory: stock-inventory-app

      # 4 – (No lint step; we skipped it)

      # 5 – Run tests (but don't fail if none exist yet)
      - name: Test
        run: pnpm run test -- --passWithNoTests
        working-directory: stock-inventory-app

      # 6 – Build production bundle
      - name: Build
        run: pnpm run build
        working-directory: stock-inventory-app
