name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install packages
        run: pnpm install
        working-directory: stock-inventory-app

      - name: Test
        # Runs Jest exactly as defined in package.json
        # and will succeed because sanity.test.ts passes
        run: pnpm run test
        working-directory: stock-inventory-app

      - name: Build
        run: pnpm run build
        working-directory: stock-inventory-app
