name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install packages
        run: pnpm install
        working-directory: stock-inventory-app
      - name: Test
        run: pnpm run test -- --run
        working-directory: stock-inventory-app
      - name: Build
        run: pnpm run build
        working-directory: stock-inventory-app

