name: CI

# Run this workflow on every push to any branch and on pull-requests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - uses: actions/checkout@v4

      # 2) Install pnpm (v8)
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3) Install dependencies
      - name: Install packages
        run: pnpm install
        working-directory: stock-inventory-app

      # 4) Lint
      - name: Lint
        run: pnpm run lint
        working-directory: stock-inventory-app

      # 5) Run tests (Jest / Playwright etc.)
      - name: Test
        run: pnpm run test -- --run
        working-directory: stock-inventory-app

      # 6) Build production bundle
      - name: Build
        run: pnpm run build
        working-directory: stock-inventory-app
